CREATE TABLE `th_thesaurus` (
  `id_pa` serial NOT NULL,
  `pa_name` char(150) NOT NULL,
  `pa_description` text NOT NULL,
  `pa_status` int(11) NOT NULL,
  `pa_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pa_update` date NOT NULL,
  `pa_classe` int(11) NOT NULL,
  `pa_creator` int(11) NOT NULL,
  `pa_hidden` int(11) NOT NULL DEFAULT '0',
  `pa_avaliacao` double NOT NULL,
  `pa_class` char(60) NOT NULL,
  `pa_version` varchar(10) NOT NULL,
  `pa_introdution` longtext NOT NULL,
  `pa_methodology` longtext NOT NULL,
  `pa_icone` char(50) NOT NULL,
  `pa_header` char(100) NOT NULL,
  `pa_audience` text NOT NULL,
  `pa_type` int(11) NOT NULL DEFAULT '1',
  `pa_language` int(11) NOT NULL DEFAULT '364',
  `pa_multi_language` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
