import { DOCUMENT } from '@angular/common';
import { Injectable, computed, inject, signal } from '@angular/core';

const translations = {
  'pt-br': {
    memberName: "Nome",
    memberInstitution: "Instituição",
    memberRole: "Função",
    memberAction: "Ação",
    addMembers: "Adicionar novos membros",
    memberEmailPrompt: "Informe o e-mail",
    memberSearchPlaceholder: "Digite o nome ou e-mail do usuário",
    registerMember: "Registrar",
    membershipType: "Tipo de vínculo",
    managerRole: "Autor e revisor (gerente)",
    coauthorRole: "Autor (coautor)",
    collaboratorRole: "Colaborador",
    advisorRole: "Orientador",
    typistRole: "Digitador",
    authorRole: "Autor",
    registeringMember: "Registrando...",
    noMemberResults: "Nenhum resultado encontrado.",
    removeMember: "Remover membro",
    removeMemberConfirm: "Deseja remover este membro?",
    exportDetails: "Sobre o tesauro",
    exportAuthors: "Autores",
    exportIntroduction: "Apresentação",
    exportLoadFailed: "Não foi possível carregar os dados do tesauro.",
    exportWholeThesaurus: "Ao escolher um formato, você exportará toda a base deste tesauro.",
    conceptInformation: "Informação",
    conceptGraph: "Grafo",
    conceptCard: "Ficha",
    conceptNotes: "Notas",
    conceptLog: "Log",
    conceptPanelTitle: "Conceito",
    preferredTermLabel: "Termo Preferencial",
    equivalentTermLabel: "Termo Equivalente",
    hiddenTermLabel: "Termo Oculto",
    broaderConceptLabel: "Conceito Geral (TG)",
    narrowerConceptLabel: "Conceito Específico (TE)",
    relatedConceptLabel: "Conceito Relacionado (TR)",
    termLabelFallback: "Termo",
    deleteLabelConfirm: "Tem certeza que deseja excluir este rótulo? ",
    deleteNoteConfirm: "Deseja realmente excluir esta nota?",
    noteOf: "Nota de",
    generalNotes: "Notas Gerais",
    newNote: "Nova Nota",
    noteType: "Tipo das notas",
    noteContent: "Conteúdo da nota",
    textLanguage: "Idioma do texto",
    saveNote: "Salvar Nota",
    searchInputLabel: "Termo a pesquisar",
    searchPlaceholder: "Ex: Base de Dados, Computação...",
    searching: "Pesquisando...",
    clearSearch: "Limpar busca",
    resultsFound: "Resultados encontrados",
    noResultsFound: "Nenhum resultado encontrado",
    tryDifferentTerms: "Tente pesquisar com termos diferentes.",
    searchTips: "Dicas para buscar:",
    searchTipExact: "Digite o termo exato ou parcial que deseja encontrar",
    searchTipCharacters: "Use a busca com caracteres alfabéticos ou números",
    searchTipDetails: "Clique em um resultado para ver detalhes do conceito",
    searchTipThesaurus: "Você está pesquisando no thesaurus que selecionou anteriormente",
    conceptDetails: "Detalhes do Conceito",
    loading: "Carregando...",
    created: "Criado:",
    dataTitle: "Dados",
    preferredLabels: "Preferenciais",
    alternativeLabels: "Alternativos",
    hiddenLabels: "Ocultos",
    noLabels: "Nenhum label definido",
    broaderConcepts: "Mais Amplos",
    narrowerConcepts: "Mais Específicos",
    relatedConcepts: "Relacionados",
    notesTitle: "Notas",
    noRelations: "Nenhuma relação definida",
    copyTerm: "Copiar termo",
    openNewTab: "Abrir em Nova Aba",
    enterSearchTerm: "Por favor, digite um termo para pesquisar.",
    selectThesaurusFirst: "Nenhum thesaurus selecionado. Por favor, selecione um thesaurus primeiro.",
    searchFailed: "Erro ao realizar a busca. Tente novamente.",
    invalidConceptId: "ID do conceito inválido",
    noConceptData: "Nenhum dado retornado do servidor",
    loadConceptFailed: "Erro ao carregar detalhes. Tente novamente.",
    termCopied: "Termo copiado: ",
    copyTermFailed: "Erro ao copiar o termo",
    candidateTerms: "Termos para candidatos a conceito",
    selectAll: "Selecionar tudo",
    deselectAll: "Desmarcar tudo",
    createConcept: "Criar conceito",
    close: "Fechar",

    publicDescription: "O Thesa está disponível para qualquer pessoa visualizar, sem restrições de acesso.",
    privateDescription: "O Thesa é restrito e somente usuários autorizados podem visualizá-lo.",
    cancelledDescription: "O Thesa foi invalidado ou desativado, estando indisponível para visualização pública ou privada.",
    confirmVisibilityChange: "Você tem certeza que deseja alterar a visibilidade do Thesa?",
    imageUpload: "Upload de Imagem",
    chooseFile: "Escolher arquivo",
    noFileChosen: "Nenhum arquivo selecionado",
    imagePreview: "Prévia da imagem",
    invalidImage: "Por favor, selecione uma imagem válida.",
    uploadCompleted: "Upload concluído com sucesso!",
    uploadFailed: "Erro no upload. Tente novamente.",

    confirmLicenseChange: "Você tem certeza que deseja alterar a licença do Thesa?",
    reservedCopyright: "Reservado & Copyright",
    submit: "Enviar",
    note: "Observação",
    portugueseBrazil: "Português (Brasil)",
    english: "Inglês",
    spanish: "Espanhol",
    french: "Francês",
    italian: "Italiano",
    german: "Alemão",

    confirmTypeChange: "Você tem certeza que deseja alterar o tipo de thesa?",
    openThesaTitle: "Thesa Aberto",
    filterThesauri: "Filtrar tesauros por título...",
    createThesa: "Criar novo Thesa",
    publicStatus: "Público",
    privateStatus: "Privado",
    cancelledStatus: "Cancelado",
    accessThesa: "Acessar",

    termSingular: "termo",
    termPlural: "termos",
    title: "Título",
    thesaurusTitle: "Título do tesauro",
    acronym: "Acrônimo",
    save: "Salvar",
    cancel: "Cancelar",
    savedSuccessfully: "Dados salvos com sucesso!",
    thesaType: "Tipo do Thesa",
    description: "Descrição",
    vocabularyDescription: "Descrição do vocabulário / tesauro",
    methodology: "Metodologia",
    audience: "Público Alvo",
    languages: "Idiomas",
    license: "Licença",
    visibility: "Visibilidade",
    themeIcons: "Tema e Ícones",
    relationTypes: "Tipos de Relações",
    members: "Membros",
    themes: "Temas",
    relations: "Relações",
    thesaurusMembers: "Membros do tesauro",

    search: 'Pesquisar', open: 'Thesa Abertos', mine: 'Meus Thesa',
    documentation: 'Documentação', about: 'Sobre', login: 'Entrar',
    profile: 'Meu perfil', toggleNavigation: 'Alternar navegação',
    selectLanguage: 'Selecionar idioma', openLanguageSelection: 'Abrir seleção de idioma',
    concepts: 'Conceitos', conceptSingular: 'conceito', conceptPlural: 'conceitos',
    alphabeticalDisplay: 'Apresentação Alfabética', systematicDisplay: 'Apresentação Sistemática',
    export: 'Exportação', terms: 'Termos', settings: 'Configurações',
    disableEditing: 'Desativar Edição', enableEditing: 'Habilitar Edição', editingEnabled: 'EDIÇÃO ATIVADA',
    selectTerm: 'Selecione um termo para ver os detalhes.',
    searchTerm: 'Buscar termo...', unassociatedTerms: 'Termos não associados',
  },
  en: {
    memberName: "Name",
    memberInstitution: "Institution",
    memberRole: "Role",
    memberAction: "Action",
    addMembers: "Add members",
    memberEmailPrompt: "Enter an email address",
    memberSearchPlaceholder: "Enter the user's name or email address",
    registerMember: "Add member",
    membershipType: "Membership role",
    managerRole: "Author and reviewer (manager)",
    coauthorRole: "Author (coauthor)",
    collaboratorRole: "Collaborator",
    advisorRole: "Advisor",
    typistRole: "Data entry operator",
    authorRole: "Author",
    registeringMember: "Adding member...",
    noMemberResults: "No results found.",
    removeMember: "Remove member",
    removeMemberConfirm: "Do you want to remove this member?",
    exportDetails: "About the thesaurus",
    exportAuthors: "Authors",
    exportIntroduction: "Introduction",
    exportLoadFailed: "Could not load the thesaurus details.",
    exportWholeThesaurus: "Choosing a format exports the entire database of this thesaurus.",
    conceptInformation: "Information",
    conceptGraph: "Graph",
    conceptCard: "Card",
    conceptNotes: "Notes",
    conceptLog: "Log",
    conceptPanelTitle: "Concept",
    preferredTermLabel: "Preferred Term",
    equivalentTermLabel: "Equivalent Term",
    hiddenTermLabel: "Hidden Term",
    broaderConceptLabel: "Broader Concept (BT)",
    narrowerConceptLabel: "Narrower Concept (NT)",
    relatedConceptLabel: "Related Concept (RT)",
    termLabelFallback: "Term",
    deleteLabelConfirm: "Are you sure you want to delete this label? ",
    deleteNoteConfirm: "Are you sure you want to delete this note?",
    noteOf: "Note for",
    generalNotes: "General Notes",
    newNote: "New Note",
    noteType: "Note type",
    noteContent: "Note content",
    textLanguage: "Text language",
    saveNote: "Save note",
    searchInputLabel: "Search term",
    searchPlaceholder: "E.g. Database, Computing...",
    searching: "Searching...",
    clearSearch: "Clear search",
    resultsFound: "Results found",
    noResultsFound: "No results found",
    tryDifferentTerms: "Try searching with different terms.",
    searchTips: "Search tips:",
    searchTipExact: "Enter the exact or partial term you want to find",
    searchTipCharacters: "Search using letters or numbers",
    searchTipDetails: "Click a result to view concept details",
    searchTipThesaurus: "You are searching the thesaurus you selected earlier",
    conceptDetails: "Concept details",
    loading: "Loading...",
    created: "Created:",
    dataTitle: "Data",
    preferredLabels: "Preferred",
    alternativeLabels: "Alternative",
    hiddenLabels: "Hidden",
    noLabels: "No labels defined",
    broaderConcepts: "Broader",
    narrowerConcepts: "Narrower",
    relatedConcepts: "Related",
    notesTitle: "Notes",
    noRelations: "No relationships defined",
    copyTerm: "Copy term",
    openNewTab: "Open in new tab",
    enterSearchTerm: "Please enter a term to search.",
    selectThesaurusFirst: "No thesaurus selected. Please select one first.",
    searchFailed: "Search failed. Please try again.",
    invalidConceptId: "Invalid concept ID",
    noConceptData: "The server returned no data",
    loadConceptFailed: "Could not load details. Please try again.",
    termCopied: "Term copied: ",
    copyTermFailed: "Could not copy the term",
    candidateTerms: "Candidate terms for concepts",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    createConcept: "Create concept",
    close: "Close",

    publicDescription: "Thesa is available for anyone to view, without access restrictions.",
    privateDescription: "Thesa is restricted and only authorized users can view it.",
    cancelledDescription: "Thesa has been invalidated or deactivated and is unavailable for public or private viewing.",
    confirmVisibilityChange: "Are you sure you want to change the visibility of Thesa?",
    imageUpload: "Image Upload",
    chooseFile: "Choose file",
    noFileChosen: "No file chosen",
    imagePreview: "Image preview",
    invalidImage: "Please select a valid image.",
    uploadCompleted: "Upload completed successfully!",
    uploadFailed: "Upload failed. Please try again.",

    confirmLicenseChange: "Are you sure you want to change the Thesa license?",
    reservedCopyright: "All rights reserved & Copyright",
    submit: "Submit",
    note: "Note",
    portugueseBrazil: "Portuguese (Brazil)",
    english: "English",
    spanish: "Spanish",
    french: "French",
    italian: "Italian",
    german: "German",

    confirmTypeChange: "Are you sure you want to change the Thesa type?",
    openThesaTitle: "Public Thesa",
    filterThesauri: "Filter thesauri by title...",
    createThesa: "Create new Thesa",
    publicStatus: "Public",
    privateStatus: "Private",
    cancelledStatus: "Cancelled",
    accessThesa: "Open",

    termSingular: "term",
    termPlural: "terms",
    title: "Title",
    thesaurusTitle: "Thesaurus title",
    acronym: "Acronym",
    save: "Save",
    cancel: "Cancel",
    savedSuccessfully: "Data saved successfully!",
    thesaType: "Thesa type",
    description: "Description",
    vocabularyDescription: "Vocabulary / thesaurus description",
    methodology: "Methodology",
    audience: "Target audience",
    languages: "Languages",
    license: "License",
    visibility: "Visibility",
    themeIcons: "Theme and Icons",
    relationTypes: "Relationship Types",
    members: "Members",
    themes: "Themes",
    relations: "Relationships",
    thesaurusMembers: "Thesaurus members",

    search: 'Search', open: 'Public Thesa', mine: 'My Thesa',
    documentation: 'Documentation', about: 'About', login: 'Sign in',
    profile: 'My profile', toggleNavigation: 'Toggle navigation',
    selectLanguage: 'Select language', openLanguageSelection: 'Open language selection',
    concepts: 'Concepts', conceptSingular: 'concept', conceptPlural: 'concepts',
    alphabeticalDisplay: 'Alphabetical Display', systematicDisplay: 'Systematic Display',
    export: 'Export', terms: 'Terms', settings: 'Settings',
    disableEditing: 'Disable Editing', enableEditing: 'Enable Editing', editingEnabled: 'EDITING ENABLED',
    selectTerm: 'Select a term to view its details.',
    searchTerm: 'Search for a term...', unassociatedTerms: 'Unassociated terms',
  },
  es: {
    memberName: "Nombre",
    memberInstitution: "Institución",
    memberRole: "Función",
    memberAction: "Acción",
    addMembers: "Añadir miembros",
    memberEmailPrompt: "Introduzca un correo electrónico",
    memberSearchPlaceholder: "Escriba el nombre o correo electrónico del usuario",
    registerMember: "Añadir miembro",
    membershipType: "Tipo de vínculo",
    managerRole: "Autor y revisor (gestor)",
    coauthorRole: "Autor (coautor)",
    collaboratorRole: "Colaborador",
    advisorRole: "Asesor",
    typistRole: "Digitador",
    authorRole: "Autor",
    registeringMember: "Añadiendo miembro...",
    noMemberResults: "No se encontraron resultados.",
    removeMember: "Eliminar miembro",
    removeMemberConfirm: "¿Desea eliminar a este miembro?",
    exportDetails: "Sobre el tesauro",
    exportAuthors: "Autores",
    exportIntroduction: "Introducción",
    exportLoadFailed: "No se pudieron cargar los datos del tesauro.",
    exportWholeThesaurus: "Al elegir un formato, se exportará toda la base de datos de este tesauro.",
    conceptInformation: "Información",
    conceptGraph: "Grafo",
    conceptCard: "Ficha",
    conceptNotes: "Notas",
    conceptLog: "Registro",
    conceptPanelTitle: "Concepto",
    preferredTermLabel: "Término preferente",
    equivalentTermLabel: "Término equivalente",
    hiddenTermLabel: "Término oculto",
    broaderConceptLabel: "Concepto genérico (TG)",
    narrowerConceptLabel: "Concepto específico (TE)",
    relatedConceptLabel: "Concepto relacionado (TR)",
    termLabelFallback: "Término",
    deleteLabelConfirm: "¿Seguro que desea eliminar esta etiqueta? ",
    deleteNoteConfirm: "¿Seguro que desea eliminar esta nota?",
    noteOf: "Nota de",
    generalNotes: "Notas generales",
    newNote: "Nueva nota",
    noteType: "Tipo de nota",
    noteContent: "Contenido de la nota",
    textLanguage: "Idioma del texto",
    saveNote: "Guardar nota",
    searchInputLabel: "Término de búsqueda",
    searchPlaceholder: "Ej.: Base de datos, Informática...",
    searching: "Buscando...",
    clearSearch: "Limpiar búsqueda",
    resultsFound: "Resultados encontrados",
    noResultsFound: "No se encontraron resultados",
    tryDifferentTerms: "Pruebe a buscar otros términos.",
    searchTips: "Consejos de búsqueda:",
    searchTipExact: "Escriba el término exacto o parcial que desea encontrar",
    searchTipCharacters: "Busque usando letras o números",
    searchTipDetails: "Haga clic en un resultado para ver los detalles del concepto",
    searchTipThesaurus: "Está buscando en el tesauro que seleccionó anteriormente",
    conceptDetails: "Detalles del concepto",
    loading: "Cargando...",
    created: "Creado:",
    dataTitle: "Datos",
    preferredLabels: "Preferentes",
    alternativeLabels: "Alternativos",
    hiddenLabels: "Ocultos",
    noLabels: "No hay etiquetas definidas",
    broaderConcepts: "Más amplios",
    narrowerConcepts: "Más específicos",
    relatedConcepts: "Relacionados",
    notesTitle: "Notas",
    noRelations: "No hay relaciones definidas",
    copyTerm: "Copiar término",
    openNewTab: "Abrir en una pestaña nueva",
    enterSearchTerm: "Escriba un término para buscar.",
    selectThesaurusFirst: "No se ha seleccionado un tesauro. Seleccione uno primero.",
    searchFailed: "Error al buscar. Inténtelo de nuevo.",
    invalidConceptId: "ID de concepto no válido",
    noConceptData: "El servidor no devolvió datos",
    loadConceptFailed: "No se pudieron cargar los detalles. Inténtelo de nuevo.",
    termCopied: "Término copiado: ",
    copyTermFailed: "No se pudo copiar el término",
    candidateTerms: "Términos candidatos a concepto",
    selectAll: "Seleccionar todo",
    deselectAll: "Desmarcar todo",
    createConcept: "Crear concepto",
    close: "Cerrar",

    publicDescription: "Thesa está disponible para que cualquier persona lo consulte, sin restricciones de acceso.",
    privateDescription: "Thesa es restringido y solo los usuarios autorizados pueden consultarlo.",
    cancelledDescription: "Thesa ha sido invalidado o desactivado y no está disponible para consulta pública ni privada.",
    confirmVisibilityChange: "¿Está seguro de que desea cambiar la visibilidad de Thesa?",
    imageUpload: "Subir imagen",
    chooseFile: "Elegir archivo",
    noFileChosen: "Ningún archivo seleccionado",
    imagePreview: "Vista previa de la imagen",
    invalidImage: "Seleccione una imagen válida.",
    uploadCompleted: "¡Imagen subida correctamente!",
    uploadFailed: "Error al subir la imagen. Inténtelo de nuevo.",

    confirmLicenseChange: "¿Está seguro de que desea cambiar la licencia de Thesa?",
    reservedCopyright: "Derechos reservados y Copyright",
    submit: "Enviar",
    note: "Nota",
    portugueseBrazil: "Portugués (Brasil)",
    english: "Inglés",
    spanish: "Español",
    french: "Francés",
    italian: "Italiano",
    german: "Alemán",

    confirmTypeChange: "¿Está seguro de que desea cambiar el tipo de Thesa?",
    openThesaTitle: "Thesa abiertos",
    filterThesauri: "Filtrar tesauros por título...",
    createThesa: "Crear nuevo Thesa",
    publicStatus: "Público",
    privateStatus: "Privado",
    cancelledStatus: "Cancelado",
    accessThesa: "Acceder",

    termSingular: "término",
    termPlural: "términos",
    title: "Título",
    thesaurusTitle: "Título del tesauro",
    acronym: "Acrónimo",
    save: "Guardar",
    cancel: "Cancelar",
    savedSuccessfully: "¡Datos guardados correctamente!",
    thesaType: "Tipo de Thesa",
    description: "Descripción",
    vocabularyDescription: "Descripción del vocabulario / tesauro",
    methodology: "Metodología",
    audience: "Público objetivo",
    languages: "Idiomas",
    license: "Licencia",
    visibility: "Visibilidad",
    themeIcons: "Tema e Iconos",
    relationTypes: "Tipos de Relaciones",
    members: "Miembros",
    themes: "Temas",
    relations: "Relaciones",
    thesaurusMembers: "Miembros del tesauro",

    search: 'Buscar', open: 'Thesa abiertos', mine: 'Mis Thesa',
    documentation: 'Documentación', about: 'Acerca de', login: 'Iniciar sesión',
    profile: 'Mi perfil', toggleNavigation: 'Alternar navegación',
    selectLanguage: 'Seleccionar idioma', openLanguageSelection: 'Abrir selección de idioma',
    concepts: 'Conceptos', conceptSingular: 'concepto', conceptPlural: 'conceptos',
    alphabeticalDisplay: 'Presentación alfabética', systematicDisplay: 'Presentación sistemática',
    export: 'Exportación', terms: 'Términos', settings: 'Configuración',
    disableEditing: 'Desactivar edición', enableEditing: 'Habilitar edición', editingEnabled: 'EDICIÓN ACTIVADA',
    selectTerm: 'Seleccione un término para ver los detalles.',
    searchTerm: 'Buscar término...', unassociatedTerms: 'Términos no asociados',
  },
} as const;

export type Language = keyof typeof translations;

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  private readonly storageKey = 'thesa_locale';
  private readonly selected = signal<Language>('pt-br');
  readonly currentLanguage = this.selected.asReadonly();
  readonly labels = computed(() => translations[this.selected()]);
  readonly options = [
    { code: 'pt-br', label: 'Português', flagSrc: 'assets/img/flags/br.svg' },
    { code: 'en', label: 'English', flagSrc: 'assets/img/flags/gb.svg' },
    { code: 'es', label: 'Español', flagSrc: 'assets/img/flags/es.svg' },
  ] as const;
  readonly selectedOption = computed(() =>
    this.options.find(option => option.code === this.selected()) ?? this.options[0]
  );

  constructor() {
    try {
      const saved = this.document.defaultView?.localStorage.getItem(this.storageKey);
      if (this.isLanguage(saved)) this.selected.set(saved);
    } catch {
      // Keep the default when browser storage is unavailable.
    }
  }

  setLanguage(language: string): void {
    if (!this.isLanguage(language)) return;
    this.selected.set(language);
    try {
      this.document.defaultView?.localStorage.setItem(this.storageKey, language);
    } catch {
      // Language switching still works when persistence is blocked.
    }
  }

  private isLanguage(value: unknown): value is Language {
    return value === 'pt-br' || value === 'en' || value === 'es';
  }
}
